<?php 
function createTables(){
	include('../config.php');
	// Create Thing Table
	// Ref: https://schema.org/Thing
	$thing = "CREATE TABLE Thing(
		id INT(11) AUTO_INCREMENT PRIMARY KEY,
		additionalType VARCHAR(250),
		alternateName VARCHAR(250),
		description TEXT,
		disambiguatingDescription TEXT,
		identifier TEXT,
		image VARCHAR(250),
		#mainEntityOfPage INT(11),
		mainEntityOfPage VARCHAR(250),
		name VARCHAR(250),
		potentialAction TEXT,
		sameAs VARCHAR(250),
		subjectOf TEXT,
		url VARCHAR(250),
		power SET('0','1'),
		recordCreated DATETIME,
		recordModified DATETIME,
		timestamp TIMESTAMP,
		UNIQUE(name)		
		)";
	$conn->query($thing);
	// Create Organization Table
	// Ref: https://schema.org/Organization
	$organization = "CREATE TABLE Organization(
		id INT(11) AUTO_INCREMENT PRIMARY KEY,
		actionableFeedbackPolicy TEXT,
		address VARCHAR(250),
		aggregateRating INT(11),
		company VARCHAR(150),
		alumni TEXT,
		areaServed TEXT,
		award TEXT,
		brand INT(11),
		contactPoint INT(11),
		correctionsPolicy VARCHAR(250),
		#correctionsPolicy INT(11),
		department INT(11),
		dissolutionDate DATETIME,
		diversityPolicy VARCHAR(250),
		#diversityPolicy INT(11),
		diversityStaffingReport VARCHAR(250),
		#diversityStaffingReport INT(11),
		duns VARCHAR(150),
		email VARCHAR(150),
		employee INT(11),
		ethicsPolicy VARCHAR(250),
		#ethicsPolicy INT(11),
		event  INT(11),
		faxNumber VARCHAR(150),
		founder INT(11),
		foundedDate DATETIME,
		foundingLocation INT(11),
		funder TEXT,
		globalLocationNumber INT(13),
		hasCredential TEXT,
		hasOfferCatalog TEXT,
		hasPOS TEXT,
		hasProductReturnPolicy VARCHAR(250),
		#hasProductReturnPolicy INT(11),
		isicV4 VARCHAR(100),
		knowsAbout TEXT,
		knowsLanguage TEXT,
		legalName VARCHAR(250),
		leiCode VARCHAR(250),
		location TEXT,
		logo VARCHAR(250),
		makesOffer TEXT,
		member TEXT,
		memberOf TEXT,
		naics VARCHAR(250),
		numberOfEmployees INT(11),
		ownershipFundingInfo VARCHAR(250),
		#ownershipFundingInfo INT(11),
		publishingPrinciples VARCHAR(250),
		#publishingPrinciples INT(11),
		seeks TEXT,
		slogan VARCHAR(250),
		sponsor TEXT,
		subOrganization TEXT,
		taxID VARCHAR(250),
		telephone VARCHAR(30),
		unnamedSourcesPolicy VARCHAR(250),
		#unnamedSourcesPolicy INT(11),
		vatID VARCHAR(250),
		power SET('0','1'),
		recordCreated DATETIME,
		recordModified DATETIME,
		timestamp TIMESTAMP
		)";
	$conn->query($organization);

	// Create Person Table
	// Ref: https://schema.org/Person
	$person = "CREATE TABLE Person(
		id INT(11) AUTO_INCREMENT PRIMARY KEY,
		additionalName VARCHAR(250),
		address VARCHAR(250),
		affiliation TEXT,
		alumniOf TEXT,
		award TEXT,
		birthDate DATETIME,
		birthPlace INT(11),
		brand TEXT,
		callSign VARCHAR(250),
		children TEXT,
		colleague TEXT,
		contactPoint INT(11),
		deathDate DATETIME,
		deathPlace INT(11),
		duns VARCHAR(150),
		email VARCHAR(150),
		familyName VARCHAR(250),
		faxNumber VARCHAR(30),
		follows TEXT,
		funder TEXT,
		gender SET('M','F'),
		givenName VARCHAR(250),
		globalLocationNumber INT(13),
		hasCredential TEXT,
		hasOccupation INT(13),
		hasOfferCatalog TEXT,
		hasPOS TEXT,
		height INT(11),
		homeLocation INT(11),
		honorificPrefix VARCHAR(100),
		honorificSuffix VARCHAR(100),
		isicV4 VARCHAR(100),
		jobTitle VARCHAR(250),
		knows TEXT,
		knowsAbout TEXT,
		knowsLanguage TEXT,
		makesOffer TEXT,
		memberOf TEXT,
		naics VARCHAR(250),
		nationality TEXT,
		netWorth INT(11),
		owns TEXT,
		parent TEXT,
		performerIn TEXT,
		publishingPrinciples VARCHAR(250),
		#publishingPrinciples INT(11),
		relatedTo TEXT,
		seeks TEXT,
		sibling TEXT,
		sponsor TEXT,
		taxID VARCHAR(250),
		telephone VARCHAR(30),
		vatID VARCHAR(250),
		weight INT(11),
		workLocation INT(11),
		worksFor INT(11),
		power SET('0','1'),
		recordCreated DATETIME,
		recordModified DATETIME,
		timestamp TIMESTAMP
		)";
	$conn->query($person);
	// Create Place Table
	// Ref: https://schema.org/Place
	$place = "CREATE TABLE Place(
		id INT(11) AUTO_INCREMENT PRIMARY KEY,
		additionalproperty TEXT,
		address VARCHAR(250),
		aggregateRating INT(11),
		amenityFeature TEXT,
		branchCode VARCHAR(100),
		containedInPlace INT(11),
		event  INT(11),
		faxNumber VARCHAR(150),
		geo INT(11),
		geoContains TEXT,
		geoCoveredBy TEXT,
		geoCovers TEXT,
		geoCrosses TEXT,
		geoDisjoint TEXT,
		geoEquals TEXT,
		geoIntersects TEXT,
		geoOverlaps TEXT,
		geoTouches TEXT,
		geoWithin TEXT,
		globalLocationNumber INT(13),
		hasMap VARCHAR(150),
		isAccessibleForFree SET('0','1'),
		isicV4 VARCHAR(100),
		latitude VARCHAR(150),
		logo VARCHAR(250),
		longitude VARCHAR(150),
		maximumAttendeeCaoacity INT(11),
		openingHoursSpecification INT(11),
		photo TEXT,
		publicAccess SET('0','1'),
		review TEXT,
		slogan VARCHAR(250),
		smokingAllowed SET('0','1'),
		specialOpeningHoursSpecification INT(11),
		telephone VARCHAR(30),
		power SET('0','1'),
		recordCreated DATETIME,
		recordModified DATETIME,
		timestamp TIMESTAMP		
		)";
	$conn->query($place);
	// Create CreativeWork Table
	// Ref: https://schema.org/CreativeWork
	$creativeWork = "CREATE TABLE CreativeWork(
		id INT(11) AUTO_INCREMENT PRIMARY KEY,
		about VARCHAR(250),
		abstract TEXT,
		accessMode TEXT,
		accessModeSufficient TEXT,
		accessibilityAPI TEXT,
		accessibilityControl TEXT,
		accessibilityFeature VARCHAR(250),
		accessibilityHazard TEXT,
		accessibilitySummary TEXT,
		accountablePerson INT(11),
		aggregateRating INT(11),
		alternativeHeadline VARCHAR(250),
		associatedMedia TEXT,
		audience TEXT,
		audio INT(11),
		author TEXT,
		award TEXT,
		character TEXT,
		citation TEXT,
		comment TEXT,
		commentCount INT(11),
		conditionsOfAccess VARCHAR(500),
		contentLocation TEXT,
		contentRating INT(11),
		contentReferenceTime DATETIME,
		contributor TEXT,
		copyrightHolder TEXT,
		copyrightYear INT(5),
		correction TEXT,
		creativeWorkStatus VARCHAR(150),
		creator TEXT,
		dateCreated DATETIME,
		dateModified DATETIME,
		datePublished DATETIME,
		discussionURL VARCHAR(250),
		editor TEXT,
		educationalAlignment TEXT,
		educationalUse VARCHAR(250),
		encoding INT(11),
		encodingFormat VARCHAR(250),
		exampleOfWork TEXT,
		expires DATETIME,
		funder TEXT,
		genre VARCHAR(250),
		hasPart TEXT,
		headline VARCHAR(250),
		inLanguage TEXT,
		interactionStatistic INT(11),
		interactionType VARCHAR(250),
		isAccessibleForFree SET('0','1'),
		isBasedOn TEXT,
		isFamilyFriendly SET('0','1'),
		isPartOf TEXT,
		keywords VARCHAR(250),
		learningResourceType VARCHAR(250),
		license VARCHAR(250),
		locationCreated INT(11),
		mainEntity TEXT,
		material TEXT,
		materialExtent TEXT,
		mentions TEXT,
		offers TEXT,
		position INT(11),
		producer TEXT,
		provider TEXT,
		publicationEvent INT(11),
		publisher TEXT,
		publisherImprint INT(11),
		publishingPrinciples VARCHAR(250),
		recordedAt INT(11),
		releasedEvent INT(11),
		review TEXT,
		schemaVersion VARCHAR(250),
		sdDatePublished DATETTIME,
		sdLicense VARCHAR(250),
		sdPublisher INT(11),
		sourceOrganization INT(11),
		spatial INT(11),
		spatialCoverage INT(11),
		sponsor TEXT,
		temporal DATETIME,
		temporalCoverage TEXT,
		cwtext TEXT,
		thumbnailUrl VARCHAR(250),
		timeRequired VARCHAR(250),
		translationOfWork INT(11),
		translator TEXT,
		typicalAgeRange VARCHAR(100),
		version VARCHAR(250)
		video TEXT,
		workExample TEXT,
		workTranslation TEXT,
		power SET('0','1'),
		recordCreated DATETIME,
		recordModified DATETIME,
		timestamp TIMESTAMP		
		)";
	$conn->query($creativeWork);
}

// ****** DEBUG Table Setup ******* //
/*

*/
createTables();
mysqli_close($conn);
#header('Location:../admin/');
?>